# fly.toml file generated for utility on 2022-04-29T10:00:46-04:00

app = "utility"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  ECTO_IPV6 = "true"
  PORT = 4000
  STORAGE_DIR = "/storage/utility"

[deploy]
  release_command = "/app/bin/utility eval 'Utility.Release.migrate()'"

[experimental]
  private_network=true
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"

[mounts]
  source="utility_data"
  destination="/storage"
